//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Interface_UI.DAO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLyDaiLyEntities : DbContext
    {
        public QuanLyDaiLyEntities()
            : base("name=QuanLyDaiLyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_BC_CongNo> tb_BC_CongNo { get; set; }
        public virtual DbSet<tb_BC_DoanhSo> tb_BC_DoanhSo { get; set; }
        public virtual DbSet<tb_ChiTiet_XuatHang> tb_ChiTiet_XuatHang { get; set; }
        public virtual DbSet<tb_DaiLy> tb_DaiLy { get; set; }
        public virtual DbSet<tb_HangHoa> tb_HangHoa { get; set; }
        public virtual DbSet<tb_LoaiDaiLy> tb_LoaiDaiLy { get; set; }
        public virtual DbSet<tb_PhieuThuTien> tb_PhieuThuTien { get; set; }
        public virtual DbSet<tb_PhieuXuatHang> tb_PhieuXuatHang { get; set; }
        public virtual DbSet<tb_Quan> tb_Quan { get; set; }
        public virtual DbSet<tb_TaiKhoan> tb_TaiKhoan { get; set; }
        public virtual DbSet<tb_TienNoPhatSinh> tb_TienNoPhatSinh { get; set; }
    }
}
