//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Interface_UI.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_BC_CongNo
    {
        public int Ma_BC_CongNo { get; set; }
        public int Ma_DaiLy { get; set; }
        public System.DateTime Ngay_lap { get; set; }
        public double No_Dau { get; set; }
        public double Phat_Sinh { get; set; }
        public double No_Cuoi { get; set; }
    
        public virtual tb_DaiLy tb_DaiLy { get; set; }
    }
}
