//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Interface_UI.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ChiTiet_XuatHang
    {
        public int Ma_ChiTiet_XuatHang { get; set; }
        public int Ma_PhieuXuat { get; set; }
        public int Ma_HangHoa { get; set; }
        public int So_Luong { get; set; }
        public double Don_Gia { get; set; }
        public double Thanh_Tien { get; set; }
    
        public virtual tb_HangHoa tb_HangHoa { get; set; }
        public virtual tb_PhieuXuatHang tb_PhieuXuatHang { get; set; }
    }
}
