//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Interface_UI.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_DaiLy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_DaiLy()
        {
            this.tb_BC_CongNo = new HashSet<tb_BC_CongNo>();
            this.tb_BC_DoanhSo = new HashSet<tb_BC_DoanhSo>();
            this.tb_PhieuThuTien = new HashSet<tb_PhieuThuTien>();
            this.tb_PhieuXuatHang = new HashSet<tb_PhieuXuatHang>();
            this.tb_TienNoPhatSinh = new HashSet<tb_TienNoPhatSinh>();
        }
    
        public int Ma_DaiLy { get; set; }
        public string Ten_DaiLy { get; set; }
        public string Dien_Thoai { get; set; }
        public int Ma_Quan { get; set; }
        public string Email { get; set; }
        public int Ma_Loai_DaiLy { get; set; }
        public string Dia_Chi { get; set; }
        public System.DateTime Ngay_Tiep_Nhan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_BC_CongNo> tb_BC_CongNo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_BC_DoanhSo> tb_BC_DoanhSo { get; set; }
        public virtual tb_LoaiDaiLy tb_LoaiDaiLy { get; set; }
        public virtual tb_Quan tb_Quan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_PhieuThuTien> tb_PhieuThuTien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_PhieuXuatHang> tb_PhieuXuatHang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_TienNoPhatSinh> tb_TienNoPhatSinh { get; set; }
    }
}
