//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Interface_UI.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_HangHoa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_HangHoa()
        {
            this.tb_ChiTiet_XuatHang = new HashSet<tb_ChiTiet_XuatHang>();
        }
    
        public int Ma_HangHoa { get; set; }
        public string Ten_HangHoa { get; set; }
        public double Don_Gia { get; set; }
        public string DonVi_Tinh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_ChiTiet_XuatHang> tb_ChiTiet_XuatHang { get; set; }
    }
}
