//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Interface_UI.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_PhieuThuTien
    {
        public int Ma_PhieuThu { get; set; }
        public int Ma_DaiLy { get; set; }
        public System.DateTime Ngay_Lap { get; set; }
        public double So_Tien_Thu { get; set; }
        public string GhiChu { get; set; }
    
        public virtual tb_DaiLy tb_DaiLy { get; set; }
    }
}
